### ISSUE TITLE
App not installing, stuck on "Waiting..."

### ISSUE THREAD

**Issue by ExeRhythm** [SignTools/ios-signer-service#10]
When I hit "Install" button, the app appears on the Home screen, but is not downloading. Here's a screenshot.
![IMG_1109](https://user-images.githubusercontent.com/52459150/109941253-03055180-7ce4-11eb-9a4e-505a5d772080.jpg)
I am using ngrok with https. The app is displayed as signed. Any help is appreciated. Thanks

EDIT: After about a minute, the app disappears

**Comment by ViRb3** [comment]
In the service's configuration, `signer-cfg.yml`, what is your `server_url`? It should be the `https://` url that ngrok gives you. I just tested this scenario from scratch and it works perfectly.

**Comment by ExeRhythm** [comment]
Yes, it's the ngrok one.

**Comment by ViRb3** [comment]
Summing it up for the others:

We performed a lot of tests over instant messaging and concluded that this is an isolated case with @ExeRhythm's setup, and one particular app. The same setup with the same app works perfectly on my end. It could be an ISP block or similar, but since it's not impacting anybody else or any other apps, I will be closing this. If anybody has similar issues, feel free to comment and I will reopen.
