### ISSUE TITLE
cat: cert_pass.txt: No such file or directory

### ISSUE THREAD

**Issue by ExeRhythm** [SignTools/ios-signer-service#22]
Hi, I have this issue with my CI builder when uploading it with the web interface. How can I fix it? 
<img width="571" alt="Screenshot 2021-03-13 at 22 40 25" src="https://user-images.githubusercontent.com/52459150/111042174-1b483f80-844d-11eb-9e00-8efbd8a9cda9.png">
<img width="484" alt="Screenshot 2021-03-13 at 22 40 57" src="https://user-images.githubusercontent.com/52459150/111042187-2f8c3c80-844d-11eb-99b8-3016f2413de7.png">

**Comment by ViRb3** [comment]
The real error is in line 8: the job fetch request fails because the SECRET_URL is invalid. The cert_pass.txt error is just a consequence because nothing was downloaded. I guess the script should have stopped before that.

Anyway, the SECRET_URL is set automatically by the service, and it's either what you set in `server_url` in the config, or it's automatically fetched from ngrok if you ran the service with `-ngrok-port 4040`. What is your case?

**Comment by ExeRhythm** [comment]
I ran it using the second method you described

**Comment by ExeRhythm** [comment]
I fixed this problem by re-running ngrok and iOS Signer Service. Now everything is working fine! Thanks
