### ISSUE TITLE
«The job running on runner Hosted Agent has exceeded the maximum execution time of 10 minutes.»

### ISSUE THREAD

**Issue by ExeRhythm** [SignTools/ios-signer-service#23]
Hi, I just uploaded a large .ipa file and it seems that it could not be signed in under 10 minutes. Are there any workarounds to this? Can I manually sign it using my Mac? Thanks
![50157A86-8FB2-4402-8E9C-6A29480C3E29](https://user-images.githubusercontent.com/52459150/111045559-91ed3900-845d-11eb-9c19-266e3c874f2c.jpeg)

**Comment by ViRb3** [comment]
Can you please show the logs inside the `sign` job? Signing shouldn't normally take more than 10 minutes.

**Comment by ExeRhythm** [comment]
Sure
![image](https://user-images.githubusercontent.com/52459150/111051888-7ab34900-8467-11eb-8eb7-c7e4dda85b39.jpeg)

**Comment by ViRb3** [comment]
Oh, so it seems like it was just a big app and/or slow internet. You can control the timeout from the [sign.yml](https://github.com/SignTools/ios-signer-ci/blob/master/.github/workflows/sign.yml) file in __your__ builder. Just change:
```yml
timeout-minutes: 10
```
Make sure to match it with the `sign_timeout_mins` setting in your `signer-cfg.yml`:
```yml
sign_timeout_mins: 10
```
I will increase the timeout to 15 minutes in the next update, I hope that will be enough. Please let me know what timeout works for you.

**Comment by ViRb3** [comment]
After further discussion in private, turns out the app was 800MB, and coupled with ngrok, this of course results in a lot of waiting. You could set the timeout to a huge amount or disable it entirely, but bear in mind that this will eat your monthly allowance in GitHub. The proper solution would be to set up a real server with good upload speed and without ngrok. Otherwise, I think a timeout of 15 minutes will strike a good balance for the average use case.
